### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by victormacko** [aws/aws-sdk-php-symfony#102]
### Describe the feature

Hi there,
Symfony 7 was released recently, and it would be super awesome if this package's composer.json file could also be updated with v7 support.
Thank you for a really great package by the way -- it's very very nice!

### Use Case

Symfony 7 is the latest major update to the framework, and without subsequent updates to packages such as this one, it means users of those packages cannot update their software accordingly.

### Proposed Solution

Update references to symfony pacakges to include v7 in the composer.json file.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

latest

### Environment details (OS name and version, etc.)

OSX, latest

**Comment by yenfryherrerafeliz** [comment]
Hi @victormacko, thanks for opening this feature request. We will be looking into this soon.

Thanks!

**Comment by rhyd42** [comment]
I have checked the return types for Symfony 7, and Aws\Symfony\DependencyInjection\Configuration::getConfigTreeBuilder() has the return type specified. Adding a return type will break backwards compatibility, so this would need to be a major version change (3.x).

For Symfony 6, an @return annotation can be added to suppress the deprecation, but this should not be done until a Symfony 7 compatible version is available.

**Comment by yenfryherrerafeliz** [comment]
Hi @rhyd42, we are also planing to deprecate PHP versions below than 7.2.5, so that adding a return type here will be fine, since support for function return type was added after PHP 7. 

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @victormacko, @rhyd42, we have introduced support for Symfony 7 in the following [release](https://github.com/aws/aws-sdk-php-symfony/releases/tag/2.7.0). 

Please reach out if is there anything else we can help with.

Thanks!
