### ISSUE TITLE
setFactoryService Deprecation errors

### ISSUE THREAD

**Issue by Drusy** [aws/aws-sdk-php-symfony#11]
Hello,

using your bundle and also `symfony/phpunit-bridge` I am having tons of the following warnings :

> Symfony\Component\DependencyInjection\Definition::setFactoryService(aws_sdk) is deprecated since > version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead: 58x

Do you plan updating the bundle to get rid of these warnings ?

Regards.

**Comment by jeskew** [comment]
This is fixed in master but not in a tagged release. I can cut a release this morning.

**Comment by Drusy** [comment]
Would be appreciated if stable enough :+1:

**Comment by jeskew** [comment]
You shouldn't see the warnings anymore with [version 1.1.0](https://github.com/aws/aws-sdk-php-symfony/releases/tag/1.1.0). Please feel free to reopen if you have any questions or concerns.
