### ISSUE TITLE
How to get S3Client in Controller symfony 

### ISSUE THREAD

**Issue by zSakuraEvilz** [aws/aws-sdk-php-symfony#12]
After install aws/aws-sdk-php  and aws/aws-sdk-php-symfony. How to get S3Client in Controller symfony. Pls help me. Thank

**Comment by jeskew** [comment]
This bundle exposes an instance of `Aws\S3\S3Client` as a service named `aws.s3`. Inside of a standard Symfony controller (i.e., one that extends `Symfony\Bundle\FrameworkBundle\Controller\Controller`), you can get the the S3 client by calling `$this->get('aws.s3')`. If you're [defining your controllers as services](http://symfony.com/doc/current/cookbook/controller/service.html), you can also [inject the `aws.s3` service](http://symfony.com/doc/current/book/service_container.html#referencing-injecting-services).

Hope that helps!

**Comment by zSakuraEvilz** [comment]
Thank you
