### ISSUE TITLE
Annotation error : @http in method Aws\AwsClientInterface::getCommand()

### ISSUE THREAD

**Issue by GCalmels** [aws/aws-sdk-php-symfony#22]
Hey,

I have this error :
The annotation "@http" in method Aws\AwsClientInterface::getCommand() was never imported.
when I try to use S3.
Symfony thinks that "@http" is an annotation, is it possible to do otherwise?

Thanks

**Comment by cjyclaire** [comment]
@GCalmels Hi, my apology first but this repo is basically just setting up the integration interface for `Symfony` for you. This repo cannot help change `Symfony` mechanism. May I ask does client level configuration doesn't work for you?

**Comment by GCalmels** [comment]
Hi,
I use [OneupFlysystemBundle](https://github.com/1up-lab/OneupFlysystemBundle) with S3 : league/flysystem-aws-s3-v3. And my configuration is like [this](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/doc/adapter_awss3.md). I used factory_class and factory_method before (with success) but now it is deprecated... So I tried to update for v3 and now I have the @http error...

**Comment by cjyclaire** [comment]
@GCalmels Hmm, okay, actually, could you show me some code snippet that could reproduce this issue? Just want to confirm that basic usage is correct in case we missing something obvious.
If so, this might be a problem you would need to fire with ` OneupFlysystemBundle` or symfony.

**Comment by GCalmels** [comment]
Hi, my config is exactly like the doc on [Github](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/doc/adapter_awss3.md).
I post an issue on 1upFlySystem because with factory_class and factory_method still work but with deprecated notice... 
```
factory_class: Aws\S3\S3Client
factory_method: factory // <- I do not see this method on S3Client...
```
