### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by tfe2012** [aws/aws-sdk-php-symfony#23]
Hi, maybe you can create sample project, for understanding how to use symfony sdk

**Comment by jeskew** [comment]
Hi @tfe2012,

This repository is basically just exposing AWS clients as services within Symfony's dependency injection system. The [sample configuration file](https://github.com/aws/aws-sdk-php-symfony/blob/master/tests/fixtures/config.yml) in the test suite is a pretty good example of how to use this package.
