### ISSUE TITLE
bundle fails with symfony 2.4

### ISSUE THREAD

**Issue by gggeek** [aws/aws-sdk-php-symfony#3]
I think the quick fix would be to declare that it depends on Symfony 2.5 or later.

The error is:
PHP Fatal error:  Call to undefined method Symfony\Component\DependencyInjection\Definition::setFactory() in /home/travis/build/kaliop-uk/kueueingbundle-kinesis/vendor/aws/aws-sdk-php-symfony/src/DependencyInjection/AwsExtension.php on line 53

You can see more in the Travis logs of this build: https://travis-ci.org/kaliop-uk/kueueingbundle-kinesis/jobs/78941465

**Comment by gggeek** [comment]
ps: I mention 2.4, but perhaps most important is 2.3, which is still in active support

**Comment by jeskew** [comment]
Hi @gggeek,

This is fixed [in version 1.0.1](https://github.com/aws/aws-sdk-php-symfony/commit/826c2d7e08ffe0e84ee022fd93e82b7cb31a2aa1). Would it be possible for you to bump your dependency from 1.0.0 to 1.0.1?

**Comment by jeskew** [comment]
[Version 1.0.2](https://github.com/aws/aws-sdk-php-symfony/releases/tag/1.0.2) is now compatible with Symfony 2.3 so that a 2.3 installation declaring a dependency on `aws/aws-sdk-php-symfony: ~1.0` won't pull down the broken release.
