### ISSUE TITLE
Symfony 4.0.0  compatibility

### ISSUE THREAD

**Issue by vandromedae** [aws/aws-sdk-php-symfony#32]
(PHP7.2, symfony 4.0)

Trying to install but returns the follow error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/dependency-injection v3.4.0
    - Installation request for aws/aws-sdk-php-symfony ^1.3 -> satisfiable by aws/aws-sdk-php-symfony[1.3.0].
    - Conclusion: remove symfony/console v4.0.0
    - Installation request for symfony/dependency-injection (locked at v4.0.0) -> satisfiable by symfony/dependency-injection[v4.0.0].
    - Conclusion: don't install symfony/console v4.0.0
    - aws/aws-sdk-php-symfony 1.3.0 requires symfony/dependency-injection ~2.3|~3.0 -> satisfiable by symfony/dependency-injection[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0].
- symfony/dependency-injection v2.3.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.14 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.15 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.16 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.17 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.18 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.19 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.20 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.21 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.22 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.23 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.24 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.25 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.26 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.27 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.28 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.29 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.30 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.31 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.32 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.33 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.34 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.35 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.36 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.37 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.38 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.39 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.40 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.41 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.42 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.14 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.15 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.16 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.17 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.18 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.19 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.20 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.21 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.22 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.23 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.24 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.25 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.26 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.27 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.28 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.29 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.30 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.31 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.32 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.33 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.34 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.35 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.36 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.37 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.38 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.14 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.15 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.16 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.17 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.18 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.19 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.20 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.21 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.22 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.23 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.24 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.25 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.26 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.27 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.28 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.29 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.30 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.31 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.14 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.9 conflicts with symfony/console[v4.0.0].
    - Installation request for symfony/console ^4.0 -> satisfiable by symfony/console[v4.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by trickeyone** [comment]
I'm betting that since Symfony v4 is a significant rebuild, that it's not just a matter of updating the dependencies. Are there any plans to upgrade the bundle to support Symfony v4?

**Comment by brianfreytag** [comment]
@trickeyone I don't see a reason why it would be a "significant rebuild" considering the core of Symfony4 remains unchanged. At worst, it'll just need some updated dependencies.

**Comment by brianfreytag** [comment]
@trickeyone 

It wasn't quite as cut-n-dry as just updating the versions in composer.json. I had a do a few other tweaks to update the privacy of the services being created in AwsExtension.php. The Symfony services are being created dynamically for all of the different AWS tools. Up through 3.4, all services were defined as public unless explicitly told to be private. In 4.0, one of their biggest sweeping changes was to completely reverse this, rendering previously public services unavailable from the Container. This was the only break with this Bundle, so I took care if and put in a PR
