### ISSUE TITLE
How To Authenticate a signed-in user

### ISSUE THREAD

**Issue by engharb** [aws/aws-sdk-php-symfony#36]
Hello,

May this is not the right position to ask such a question, but I have tried and searched How to authenticate a signed-in user but I did not find a clear sheet about this issue. And may I can get some help from you.

I installed this SDK successfully and I created my S3Client object succeffully. But I want to use S3Client obj to authenticate a signed-in users (from cognito users-pool), is that possible OR should I use kind of JS-SDK for this issue?

Do you have a concreted example how to?

Best regards,

**Comment by howardlopez** [comment]
The Cognito service provides [documentation on the authentication flow](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html), which would be worth looking over. 

Within the PHP SDK, the [CognitoIdentityProviderClient](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-cognito-idp-2016-04-18.html) provides the methods referenced in that workflow.
