### ISSUE TITLE
[Bug] Change signature_version

### ISSUE THREAD

**Issue by poohia** [aws/aws-sdk-php-symfony#46]
It's totaly impossible change  ̀signature_version` in this bundle .

I need change for v4 
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#signature-version

**Comment by jeskew** [comment]
The SDK uses signature version 4 by default, but [you can set any SDK configuration value via this bundle's Symfony configuration](https://github.com/aws/aws-sdk-php-symfony#configuration).

**Comment by poohia** [comment]
@jeskew Hello, do you have example ?

I have this problem `Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.`

**Comment by ajredniwja** [comment]
@poohia is this something you still need help with?
