### ISSUE TITLE
Support for upcomming Symfony 5

### ISSUE THREAD

**Issue by jvbussel** [aws/aws-sdk-php-symfony#58]
Please add support for upcomming Symfony 5.x

composer require aws/aws-sdk-php-symfony 

results currently in:

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for aws/aws-sdk-php-symfony dev-master -> satisfiable by aws/aws-sdk-php-symfony[dev-master].
    - aws/aws-sdk-php-symfony dev-master requires symfony/config ~2.3|~3.0|~4.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by lugus** [comment]
Any news on Symfony 5 compatibility?

**Comment by DeathHand** [comment]
Problem 1
    - aws/aws-sdk-php-symfony v2.0.0 requires symfony/config ~2.3|~3.0|~4.0 -> no matching package found.
    - aws/aws-sdk-php-symfony 2.0.2 requires symfony/config ~2.3|~3.0|~4.0 -> no matching package found.
    - aws/aws-sdk-php-symfony 2.0.1 requires symfony/config ~2.3|~3.0|~4.0 -> no matching package found.
    - Installation request for aws/aws-sdk-php-symfony ~2.0 -> satisfiable by aws/aws-sdk-php-symfony[2.0.1, 2.0.2, v2.0.0].

:(

**Comment by howardlopez** [comment]
Thanks @spajxo for submitting the PR. This has been released as [2.1.0](https://github.com/aws/aws-sdk-php-symfony/releases/tag/2.1.0).
