### ISSUE TITLE
Add Symfony 6 compability

### ISSUE THREAD

**Issue by evzzz** [aws/aws-sdk-php-symfony#88]
### Describe the bug

Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "Limenius\ReactBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.

### Expected Behavior

Always time

### Current Behavior

show deprecation message

### Reproduction Steps

upgrade you project for Symfony 5.4 / 6.0

### SDK version used

2.5.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by diegosch21** [comment]
Same here. In every request in my project, in the debug toolbar i see:
_Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "Aws\Symfony\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message._

**Comment by tacman** [comment]
Related: app.WARNING: Failed to generate ConfigBuilder for extension Aws\Symfony\DependencyInjection\AwsExtension. {"exception":"[object] (LogicException(code: 0): The node was expected to be an ArrayNode. This Configuration includes an edge case not supported yet. at /home/tac/ca/ac/vendor/symfony/config/Builder/ConfigBuilderGenerator.php:108)","extensionClass":"Aws\\Symfony\\DependencyInjection\\AwsExtension"} []

**Comment by yenfryherrerafeliz** [comment]
Hi @evzzz, thanks for reporting this. I have added a needs-review label so we can investigate this further. 

Thanks!

**Comment by eman1986** [comment]
I see this library has a large range of which version of Symfony it supports, even though most of them are unsupported by Symfony. I wonder if that's why this issue is present? It's also kinda silly to support PHP 5.5 since PHP 8 is the lowest version supported by PHP, everything older than that is end of life. It kinda makes me nervous to use this library.

**Comment by boskos-q** [comment]
To chip in with deprecations

> Method "Symfony\Component\DependencyInjection\Extension\ExtensionInterface::load()" might add "void" as a native return type declaration in the future. Do the same in implementation "Aws\Symfony\DependencyInjection\AwsExtension" now to avoid errors or add an explicit @return annotation to suppress this message.

@SamRemis what are the plans for pushing these fixes forward and deprecating old versions of php & symfony as discussed in #81  ?
Thanks

**Comment by yenfryherrerafeliz** [comment]
Hi @janklan, there is a feature request for Symfony 7 support already [here](https://github.com/aws/aws-sdk-php-symfony/issues/102). We will look at it soon. Please refer to that feature request for more updates.

Thanks!

**Comment by janklan** [comment]
Hey @yenfryherrerafeliz,

OK, thanks.

For the record, that PR was opened a few days **after** I asked the question.

**Comment by yenfryherrerafeliz** [comment]
Hi @diegosch21, @tacman, @eman1986, @rhyd42, @boskos-q, and @janklan, we have introduced support for Symfony 7 in the following [release](https://github.com/aws/aws-sdk-php-symfony/releases/tag/2.7.0).

Please reach out if is there anything else we can help with.

Thanks!

**Comment by carly-cloud** [comment]
Hi,

I am getting the same error for Symfony 7.2.1

```
app.WARNING: Failed to generate ConfigBuilder for extension Aws\Symfony\DependencyInjection\AwsExtension: The node was expected to be an ArrayNode. This Configuration includes an edge case not supported yet. {"exception":"[object] (LogicException(code: 0): The node was expected to be an ArrayNode. This Configuration includes an edge case not supported yet. at /www/vendor/symfony/config/Builder/ConfigBuilderGenerator.php:108)","extensionClass":"Aws\\Symfony\\DependencyInjection\\AwsExtension"} []
```

My aws.yaml looks like this:

```
when@prod:
  aws:
    version: latest
    region: eu-central-1
    credentials: ~
    DynamoDb:
      region: us-east-1

when@dev:
  aws:
    version: latest
    region: eu-central-1
    profile: staging
    DynamoDb:
      region: us-east-1
```

Can anyone guide me how to fix that?

Thanks
