### ISSUE TITLE
Add support Symfony ^6.0

### ISSUE THREAD

**Issue by max-petrovich** [aws/aws-sdk-php-symfony#90]
### Describe the bug

Your requirements ~6.0 is not semantic. Add support for newer symfony minor versions please

### Expected Behavior

Support symfony ^6.0

### Current Behavior

~6.0, doesn't support newer minor versions

### Reproduction Steps

Require symfony ^6.0 packages

### SDK version used

2.5

### Environment details (OS name and version, etc.)

all

**Comment by VincentLanglet** [comment]
https://getcomposer.org/doc/articles/versions.md#tilde-version-range-

So `~6.0` does seems to support newer minor versions.
